##
# @description CI
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
##
name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read

jobs:
  test-typescript:
    name   : TypeScript tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id  : checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id  : setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache       : npm

      - name: Install dependencies
        id  : npm-ci
        run : npm ci

      - name: Check format
        id  : npm-format-check
        run : npm run format:check

      - name: Lint
        id  : npm-lint
        run : npm run lint

  test-action:
    name   : GitHub Actions test
    runs-on: ubuntu-latest

    permissions:
      contents     : write 
      issues       : write 
      pull-requests: write 
      id-token     : write 

    steps:
      - name: Checkout
        id  : checkout
        uses: actions/checkout@v4

      - name: Test local action
        id  : test-action
        uses: ./
